---
{{- if .Values.openshiftRoute.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: weaviate
  labels:
    name: weaviate
    app: weaviate
# Stub to solve ingress API validation issues
status:
  ingress:
    - host: ""
spec:
  host: ""
  path: {{ .Values.openshiftRoute.path }}
  wildcardPolicy: {{ .Values.openshiftRoute.wildcardPolicy }}
  port:
    targetPort: {{ .Values.openshiftRoute.service.targetPort }}
{{- if .Values.openshiftRoute.tls.enabled }}
  tls:
{{- with .Values.openshiftRoute.tls }}
    termination: {{ .termination }}
    insecureEdgeTerminationPolicy: {{ .insecureEdgeTerminationPolicy }}
    {{- with .key }}
    key: |
{{ . | indent 6 }}
    {{- end }}
    {{- with .certificate }}
    certificate: |
{{ . | indent 6 }}
    {{- end }}
    {{- with .caCertificate }}
    caCertificate: |
{{ . | nindent 6 }}
    {{- end }}
    {{- with .destinationCACertificate }}
    destinationCACertificate: |
{{ . | nindent 6 }}
    {{- end }}
{{- end}}
{{- end }}
  to:
    kind: Service
    name: {{ required "A valid .Values.service.name entry required!" .Values.openshiftRoute.service.name }}
    weight: {{ .Values.openshiftRoute.service.weight }}
{{- with .Values.openshiftRoute.alternateBackends }}
  alternateBackends:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}

